version: "3.9"

services:

  minio:
    command: server /data
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
    # docker run -d -p 9000:9000 --name minio minio/minio:latest server /data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "8080:15672"
    # docker run -d -p 8080:15672 -p 5672:5672 --hostname car-host --name rabbitmq rabbitmq:3-management

  node:
    image: node:latest
    container_name: node
    ports:
      - "3000:3000"
    # docker run -it -p 3000:3000 --name node node-ws

  openalpr:
    image: openalpr
    container_name: openalpr
    # docker run -it --rm -v $(pwd):/data:ro --entrypoint /bin/bash --name openalpr-node openalpr
    # docker run -it --rm --entrypoint /bin/bash --name openalpr-node openalpr-node
